### ISSUE TITLE
Allow minicades to be stored in gists

### ISSUE THREAD

**Issue by toolness** [toolness/minicade#6]
Currently the only way to create a minicade is by building something in Thimble and tagging it accordingly. However, this has a number of limitations:
- **Mixed content issues**. Thimble uses https, which means that all those http links to cool HTML5 gaming libraries lying around the web won't work on it, among other things.
- **One limited tool**. Thimble is great for beginners, but it's easy to grow out of, and different developers prefer different tools. Ideally, a minicade game should be able to be hosted anywhere, not just on Thimble/makes.org.
- **No way to curate**. Because a minicade always includes any makes with a particular tag, it's possible for folks to "spam" a minicade's playlist. It's also not possible to include someone else's game on your minicade without tagging it properly, which likely means you'll have to trivially fork their game and add the tag to your copy. That's annoying.

To alleviate these concerns, it would be nice to allow users to alternatively specify a minicade's metadata in a gist. For instance, the following [YAML](http://yaml.org)-based gist might work:

``` yaml
title: My Awesome Game Jam
games:
  - title: Flyswat
    description: Swat the fly before time runs out!
    url: http://toolness.github.io/fancy-friday/example/game-01.html
```

If this gist was at, say, http://gist.github.com/toolness/12345, then the minicade it represents could be accessed at http://minica.de/gist/12345.
